'use client';

import React from 'react';
import Link from 'next/link';
import { useTheme } from '@/context/ThemeContext';
import { 
  Dumbbell, 
  Moon, 
  Sun,
  Zap,
  Brain,
  Volume2,
  Image as ImageIcon,
  Download,
  Sparkles,
  ArrowRight
} from 'lucide-react';

export default function Home() {
  const { isDark, toggleTheme } = useTheme();

  const features = [
    {
      icon: <Brain size={28} />,
      title: 'AI-Powered Plans',
      description: 'Personalized workout & diet plans generated by advanced AI'
    },
    {
      icon: <Volume2 size={28} />,
      title: 'Voice Guidance',
      description: 'Listen to your plans with natural-sounding AI voice'
    },
    {
      icon: <ImageIcon size={28} />,
      title: 'Visual Content',
      description: 'AI-generated images for exercises and meals'
    },
    {
      icon: <Download size={28} />,
      title: 'Export as PDF',
      description: 'Download and share your fitness plans easily'
    },
    {
      icon: <Sparkles size={28} />,
      title: 'Daily Motivation',
      description: 'Personalized quotes to keep you inspired'
    },
    {
      icon: <Zap size={28} />,
      title: 'Regenerate Plans',
      description: 'Get alternative plans with the same profile'
    }
  ];

  return (
    <div className={`min-h-screen transition-colors duration-300 ${isDark ? 'bg-slate-950' : 'bg-white'}`}>
      {/* Navigation */}
      <nav className="sticky top-0 z-50 border-b border-gray-200 dark:border-slate-800 bg-white/80 dark:bg-slate-950/80 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between py-4">
          <Link href="/" className="flex items-center gap-2 group">
            <div className="p-2 bg-blue-600 text-white rounded-lg group-hover:bg-blue-700 transition-colors">
              <Dumbbell size={24} />
            </div>
            <span className="text-xl font-bold text-gray-900 dark:text-white">FitCoach</span>
          </Link>
          <button
            onClick={toggleTheme}
            className="p-2 rounded-lg bg-gray-100 dark:bg-slate-800 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
            aria-label="Toggle theme"
          >
            {isDark ? <Sun size={20} className="text-yellow-500" /> : <Moon size={20} className="text-slate-700" />}
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center space-y-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-100 dark:bg-blue-950 rounded-full">
            <Zap size={16} className="text-blue-600 dark:text-blue-400" />
            <span className="text-sm font-medium text-blue-600 dark:text-blue-400">AI-Powered Fitness</span>
          </div>
          
          <h1 className="text-5xl sm:text-6xl font-bold text-gray-900 dark:text-white leading-tight">
            Your Personal <span className="text-blue-600">AI Fitness Coach</span>
          </h1>
          
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed">
            Get a complete personalized fitness plan in seconds. Includes custom workout routines, meal plans, voice guidance, and more - all powered by advanced AI.
          </p>

          <Link href="/app">
            <button className="mt-8 inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-4 px-8 rounded-lg transition-colors group">
              Start Your Journey
              <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
            </button>
          </Link>
        </div>
      </section>

      {/* Features Grid */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-2 text-center">What You Get</h2>
        <p className="text-center text-gray-600 dark:text-gray-400 mb-12">Everything you need for your fitness journey</p>
        
        <div className="grid md:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="p-6 rounded-xl border border-gray-200 dark:border-slate-800 bg-gray-50 dark:bg-slate-900 hover:border-blue-300 dark:hover:border-blue-700 transition-colors"
            >
              <div className="text-blue-600 dark:text-blue-400 mb-4">
                {feature.icon}
              </div>
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-12 text-center">How It Works</h2>
        
        <div className="grid md:grid-cols-4 gap-8">
          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold mx-auto mb-4">
              1
            </div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Enter Your Details</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">Tell us about your age, goals, and preferences</p>
          </div>

          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold mx-auto mb-4">
              2
            </div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">AI Generates Plan</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">Get custom workout & diet plans in seconds</p>
          </div>

          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold mx-auto mb-4">
              3
            </div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Use Your Plan</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">Follow along with voice guidance and images</p>
          </div>

          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold mx-auto mb-4">
              4
            </div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Export & Share</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">Download as PDF or regenerate new plans</p>
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="bg-gradient-to-br from-gray-50 to-gray-100 dark:from-slate-900 dark:to-slate-800 rounded-2xl p-8 border border-gray-200 dark:border-slate-700">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-8 text-center">Built With Modern Tech</h2>
          
          <div className="grid md:grid-cols-2 gap-12">
            <div>
              <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Frontend</h3>
              <ul className="space-y-2 text-gray-700 dark:text-gray-300">
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  Next.js 14
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  React 18 & TypeScript
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  Tailwind CSS & Framer Motion
                </li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold text-gray-900 dark:text-white mb-4">AI & APIs</h3>
              <ul className="space-y-2 text-gray-700 dark:text-gray-300">
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  Google Gemini API
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  ElevenLabs TTS & Replicate AI
                </li>
                <li className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-600 rounded-full"></span>
                  jsPDF for client-side export
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="bg-blue-600 dark:bg-blue-900 rounded-2xl p-12 text-center text-white">
          <h2 className="text-3xl font-bold mb-4">Ready to Transform Your Fitness?</h2>
          <p className="text-blue-100 mb-8 text-lg">Get your personalized AI fitness plan in less than a minute</p>
          <Link href="/app">
            <button className="inline-flex items-center gap-2 bg-white hover:bg-gray-100 text-blue-600 font-semibold py-3 px-8 rounded-lg transition-colors group">
              Get Started Now
              <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
            </button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-200 dark:border-slate-800 mt-20 py-12">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-600 dark:text-gray-400">
          <p className="font-semibold text-gray-900 dark:text-white mb-2">AI Fitness Coach</p>
          <p className="text-sm">© 2025. Built with Next.js, React, and AI.</p>
        </div>
      </footer>
    </div>
  );
}
