'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useTheme } from '@/context/ThemeContext';
import { Dumbbell, Moon, Sun } from 'lucide-react';

export default function Home() {
  const { isDark, toggleTheme } = useTheme();

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-slate-900 dark:to-slate-800">
      {/* Navigation */}
      <nav className="flex items-center justify-between p-6 container">
        <div className="flex items-center gap-2">
          <Dumbbell className="text-primary" size={32} />
          <h1 className="text-2xl font-bold text-primary">FitCoach AI</h1>
        </div>
        <button
          onClick={toggleTheme}
          className="p-2 rounded-lg bg-white dark:bg-slate-700 hover:bg-gray-100 dark:hover:bg-slate-600 transition-colors"
        >
          {isDark ? <Sun size={20} /> : <Moon size={20} />}
        </button>
      </nav>

      {/* Hero Section */}
      <section className="container py-20 text-center">
        <div className="max-w-3xl mx-auto slide-up">
          <h2 className="text-5xl font-bold mb-6 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            Your Personal AI Fitness Coach
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Get personalized workout and diet plans powered by advanced AI. 
            Includes voice guidance, meal images, and PDF exports.
          </p>
          <Link href="/app">
            <button className="btn-primary text-lg px-8 py-3">
              Get Started
            </button>
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="container py-16">
        <h3 className="text-3xl font-bold text-center mb-12">Features</h3>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="card">
            <div className="text-4xl mb-4">🏋️</div>
            <h4 className="text-xl font-semibold mb-2">AI Fitness Plans</h4>
            <p className="text-gray-600 dark:text-gray-400">
              Personalized workout routines based on your goals and fitness level
            </p>
          </div>
          <div className="card">
            <div className="text-4xl mb-4">🥗</div>
            <h4 className="text-xl font-semibold mb-2">Smart Diet Plans</h4>
            <p className="text-gray-600 dark:text-gray-400">
              Customized meal plans matching your dietary preferences
            </p>
          </div>
          <div className="card">
            <div className="text-4xl mb-4">🔊</div>
            <h4 className="text-xl font-semibold mb-2">Voice Guidance</h4>
            <p className="text-gray-600 dark:text-gray-400">
              Listen to your plans with natural-sounding AI voice
            </p>
          </div>
          <div className="card">
            <div className="text-4xl mb-4">🖼️</div>
            <h4 className="text-xl font-semibold mb-2">AI Images</h4>
            <p className="text-gray-600 dark:text-gray-400">
              Visual references for exercises and meals generated by AI
            </p>
          </div>
          <div className="card">
            <div className="text-4xl mb-4">📄</div>
            <h4 className="text-xl font-semibold mb-2">Export Plans</h4>
            <p className="text-gray-600 dark:text-gray-400">
              Download your fitness plan as PDF or JSON
            </p>
          </div>
          <div className="card">
            <div className="text-4xl mb-4">💬</div>
            <h4 className="text-xl font-semibold mb-2">Daily Motivation</h4>
            <p className="text-gray-600 dark:text-gray-400">
              AI-generated motivational quotes to keep you inspired
            </p>
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <section className="container py-16 bg-white dark:bg-slate-800 rounded-lg mt-16 mb-16">
        <h3 className="text-3xl font-bold text-center mb-12">Tech Stack</h3>
        <div className="grid md:grid-cols-2 gap-8">
          <div>
            <h4 className="text-xl font-semibold mb-4 text-primary">Frontend</h4>
            <ul className="space-y-2 text-gray-600 dark:text-gray-400">
              <li>✓ Next.js 14</li>
              <li>✓ React 18</li>
              <li>✓ Tailwind CSS</li>
              <li>✓ Framer Motion</li>
            </ul>
          </div>
          <div>
            <h4 className="text-xl font-semibold mb-4 text-primary">AI & APIs</h4>
            <ul className="space-y-2 text-gray-600 dark:text-gray-400">
              <li>✓ Gemini 2.5 Flash (Text)</li>
              <li>✓ ElevenLabs (TTS)</li>
              <li>✓ Nano Banana (Images)</li>
              <li>✓ Supabase (Database)</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 dark:bg-black text-white py-8 text-center">
        <p>© 2025 AI Fitness Coach. All rights reserved.</p>
        <p className="text-sm text-gray-400 mt-2">Powered by Next.js, Gemini AI, and Supabase</p>
      </footer>
    </div>
  );
}
